config/routes.rb
Rails.application.routes.draw do

    root	'welcome#index'
    resources :users
	
  	get 	'/addnew_user', to:'users#new'
  	get		'/home',  to:'welcome#index'
  	get		'/aboutus',  to:'welcome#aboutus'
    get   '/contactus', to:'welcome#contactus'
  	
  	get 	'/dashboard', to:'agent#index'
  	get		'/profile',	to:'agent#show'

    get  	'/login', to:'sessions#new'
    post 	'/login', to:'sessions#create'
    delete 	'/logout', to:'sessions#destroy'
  	
  	
  	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 }, 
  						format: { with: VALID_EMAIL_REGEX },
  						uniqueness: { case_sensitive: false }

  	has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }

  	# Returns the hash digest of the given string.
  	def User.digest(string)
  		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to '/dashboard', alert:"User Logged In"
  	else
  		redirect_to "/login", alert:"Inavlid username or password"
  	end
  end

  def destroy
  	log_out
  	redirect_to "/login", alert:"Successfully logged out"
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :set_user, only: [:show, :edit, :update, :destroy]
	#skip_before_action :authorize, only: [:new, :create, :index]
  

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	respond_to do |format|
  		if @user.save
  			format.html { redirect_to @user, notice: "User was successfully created." }
  			format.json { render action: 'show', status: :created, location: @user}
  		else
  			format.html { render action: 'new'}
  			format.json { render json: @user.errors, status: :unprocessable_entity}
  		end
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if(@user.update(user_details_params))
      redirect_to '/dashboard', alert:"successfully updated profile"
    else
      redirect_to 'edit', alert:"Cannot Update profile"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end

    def user_details_params
      params.require(:user).permit(:f_name, :l_name, :ph_no, :gender)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def aboutus
  end

  def contactus
  	
  end
end

app/helpers/agent_helper.rb
module AgentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns the current logged-in user (if any).
	def current_user
  		if session[:user_id]
      		@current_user ||= User.find_by(id: session[:user_id])
      	end
	end

	

	# Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end

  	# Logs out the current user.
  	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end

  	# Returns true if the given user is the current user.
  	def current_user?(user)
    	user == current_user
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agent/_navbarAgentPages.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <script type="text/javascript">
          $(document).ready(function() {
          $('li.active').removeClass('active');
          $('a[href="' + location.pathname + '"]').closest('li').addClass('active'); 
        });
        </script>
    </head>
    <body>
      <% if logged_in? %>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="/dashboard"><img src="/assets/redox_logo.png"style=" width: 35px; height:33px; display: inline-block; ">
                      <span style="display: inline-block;">Redox Realty Group</span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="/dashboard">Dashboard</a></li>
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <% if current_user.isadmin? %>
                            <li><%= link_to "Add New User", users_path%></li>
                          <% end %>
                          <li><%= link_to "Profile", profile_path%></li>
                          <li><%= link_to "Log out", logout_path, method: :delete %></li>
                          <li><a href="#">Page 1-3</a></li>
                        </ul>
                      </li>
                  </ul>
                </div>
            </div>
        </nav>
        <% else %>
          redirect_to "/login", alert:"You are not authorized"
        <% end %>
  </body>
</html>

app/views/agent/index.html.erb
<!DOCTYPE html>
    <html lang="en">
        <head>
        </head>
        <body>
            <% if logged_in? %>
                <%= render 'navbarAgentPages' %>
                <br>
                <br>
                <div class="container">
    		        <h3>Agents Dashboard Page</h3>
    		        <!--<p>In this example, the navigation bar is hidden on small screens and replaced by a button in the top right corner (try to re-size this window).
    		        <p>Only when the button is clicked, the navigation bar will be displayed.</p>-->
          		</div>
            <% else %>
                <script type="text/javascript">
                    alert('You are not authorized to this page');
                    window.location = '/login';
                </script>
            <% end %>
		</body>
</html>

app/views/agent/profile.html.erb
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" media="screen" href="/assets/application.scss")">
            <link rel="shortcut icon" type="image/png" href="/assets/icon.png")">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        </head>
        <body>
            <%= render 'navbarAgentPages' %>
            <div class="container">
		        <h3>Agents Profile Page</h3>
		        <p>In this example, the navigation bar is hidden on small screens and replaced by a button in the top right corner (try to re-size this window).
		        <p>Only when the button is clicked, the navigation bar will be displayed.</p>
      		</div>
		</body>
</html>

app/views/agent/show.html.erb
<!DOCTYPE html>
    <html lang="en">
        <head>
            <style type="text/css">
                .box_profile{
                    position: relative;
                    margin-left: auto;
                    margin-right: auto;
                    width: 100%;
                    min-width: 500px;
                    max-width: 650px;
                    padding: 4%;
                    border: 2px solid #dcdee2;
                    background-color: #dcdee2;
                }
                * {
                    box-sizing: border-box;
                }

                input[type=text], input[type=number], input[type=date], select{
                    width: 90%;
                    padding: 12px;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    resize: vertical;
                }

                label {
                    padding: 12px 12px 12px 20px;
                    display: inline-block;
                }

                input[type=submit] {
                    background-color: #4CAF50;
                    color: white;
                    padding: 12px 20px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                    float: right;
                }

                input[type=submit]:hover {
                    background-color: #45a049;
                }
                .col-25 {
                    float: left;
                    width: 25%;
                    margin-top: 6px;
                }

                .col-75 {
                    float: left;
                    width: 75%;
                    margin-top: 8px;
                    padding-top: 8px;
                }

                /* Clear floats after the columns */
                .row:after {
                    content: "";
                    display: table;
                    clear: both;
                }

                /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
                @media screen and (max-width: 600px) {
                    .col-25, .col-75, input[type=submit] {
                        width: 100%;
                        margin-top: 0;
                    }
                }
                button{
                    padding: 14px 50px;
                    border-radius: 6px;
                    background-color: #e0e2e5;
                    color: black;
                    border: 1px solid #b8bbc1;
                    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
                    outline: none; 
                }
                button:hover {background-color: #d4d4d6;}
            </style>
            <script>
                function chooseFile() {
                    $("#fileInput").click();
                }
            </script>
        </head>
        <body>
            <% if current_user %>
            <%= render 'navbarAgentPages' %>
            <br><br>
            <div class="container">
                <br><br>
                <h3> Profile Settings </h3> 
                <br>
                <div class="col-md-4 col-sm-4 col-xs-12 col-xs-offset-1 col-sm-offset-0">
                    <div class="box_avatar">
                        <img style="margin-left:25px;" src="assets/avatar.png" width="200" height="200" />
                        <div style="height:0px;overflow:hidden">
                            <input type="file" id="fileInput" name="fileInput" />
                        </div>
                        <br><button style="margin-left:30px;" type="button" onclick="chooseFile();">Upload Image</button>
                    </div>
                </div>
                
                <div class="col-md-8 col-sm-7 col-xs-12 ">   
                    <div class="box_profile">
                        <h4><span class="glyphicon glyphicon-user"></span>&nbsp; Personal Information </h4> 
                        <hr>
                        <form action="#">
                            <div class="row">
                                <div class="col-25">
                                    <label for="fname">First Name</label>
                                </div>
                                <div class="col-75">
                                    <input type="text" id="fname" name="firstname" placeholder="Your name..">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="lname">Last Name</label>
                                </div>
                                <div class="col-75">
                                    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="phno">Phone Number</label>
                                </div>
                                <div class="col-75">
                                    <input type="number" id="phno" name="user[ph_no]" placeholder="Phone number..." min="10" max="10">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="dob">Date of Birth</label>
                                </div>
                                <div class="col-75">
                                    <input type="date" id="dob" name="dateofbirth">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="dob">Gender</label>
                                </div>
                                <div class="col-75">
                                    <input type="radio" name="gender" value="male" checked> Male &emsp;
                                    <input type="radio" name="gender" value="female"> Female &emsp;
                                    <input type="radio" name="gender" value="other"> Other
                                </div>
                            </div>
                            <div class="row">
                                <input type="submit" value="Update Profile">
                            </div>
                            <br>
                        </form> 
                        <h4><i class="fa fa-key" aria-hidden="true"></i>&nbsp; Change Password </h4> 
                        <hr>
                        <form>
                            <div class="row">
                                <div class="col-25">
                                    <label for="currentpsw">Current Password</label>
                                </div>
                                <div class="col-75">
                                    <input type="text" id="currentpsw" name="currentpassword">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="newpsw">New Password</label>
                                </div>
                                <div class="col-75">
                                    <input type="text" id="newpsw" name="newpassword">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-25">
                                    <label for="repsw">Re-enter Password</label>
                                </div>
                                <div class="col-75">
                                    <input type="text" id="repsw" name="reenterpassword">
                                </div>
                            </div>
                            <div class="row">
                                <input type="submit" value="Update Password">
                            </div>
                        </form>
                    </div>
                </div>
      		</div>
            <%else%>
            <script type="text/javascript">
                    alert('You are not authorized to this page');
                    window.location = '/login';
                </script>

            <%end%>
		</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redox Realty Group</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="shortcut icon" type="image/png" href="/assets/redox_logo.png">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if logged_in? && current_user.isadmin? %>
	<%= render '/agent/navbarAgentPages' %>   <br><br><br>
	<div class="container">
		<h1>Listing Users</h1>
		<% if notice %>
			<p id="notice"> <%= notice %>
			</p>
		<% end %>
		<table>
			<thead>
				<tr>
					<th>Email</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= user.email %></td>
					<%-#<% if current_user.isadmin? && !current_user?(user) %>
		    			<%-#| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
		 			 <%-# <% end %>
					
				</tr>
				<% end %>
			</tbody>
		</table>
		<br>
		<a href="/addnew_user" data-toggle="modal" data-target="#myModal">Add new User</a>
		<div class="modal fade" id="myModal">
 			<div class="modal-dialog">
  				<div class="modal-content">
  				</div>
			</div>
		</div>
		<br>
<% end %>

app/views/users/new.html.erb
<% if logged_in? && current_user.isadmin? %>

<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>

		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Add New user</h4>
		</div>
		<div class="modal-body">
		<%= render 'form' %>
		</div>				
	</body>
</html>

<% end %>

app/views/users/show.html.erb
<%= @user.email %>
<br><%= link_to 'Back', users_path %>

app/views/welcome/_footerStaticPages.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css">
            .pageContentWrapper{
                margin-bottom:100px;/* Height of footer*/
            } 
            footer{
                position:relative;
                padding: 20px 0;
                bottom:0;
                left: 0;
                right: 0;
                width: 100%;
                background:#040a24;
                display: block;
                overflow: hidden;
            }
            ul li {
                list-style: none;
            }
        </style>
    </head>
    <body>
        <footer>
            <div class="col-sm-10 col-sm-offset-1 col-xs-12">
                <div class="col-md-12" >
                    <div class="col-lg-3 col-md-4 col-xs-3">
                        <div>
                            <p style="color: #aaacaf;">© 2018 Redox Realty Group - Licensed Real Estate Brokers</p> <a style="color: #aaacaf; font-family: Helvetica !important; font-size: 13px; display: block;" href="#"><b>Privacy Policy</b></a>
                        </div>
                        <a href="/home"><img alt="logo" src="/assets/redox_logo.png" height="51px" width="53px"></a>
                    </div>
                    <div class="col-lg-9 col-md-8 col-xs-9">
                        <div class="col-md-8 col-xs-8">
                            <ul class="col-md-6 col-xs-4">  
                                <li style="color: #eff1f4;">Company</li>
                                <li><a href="/home" style="color: #aaacaf;">Home</a></li>
                                <li><a href="/aboutus" style="text-decoration: none; outline: none;opacity: 1; color: #aaacaf;">About Us</a></li>
                                <li><a href="/contactus" style="text-decoration: none; outline: none;opacity: 1; color: #aaacaf;">Contact Us</a></li>
                            </ul>
                            <ul class="col-md-6 col-xs-4" >
                                <li style="color: #eff1f4;">Get in Touch</li>
                                <li style="color: #aaacaf;"><span class="glyphicon glyphicon-phone-alt"></span>  917.346.6412</li>
                                <li><a href="mailto:info@rrh.com" style="opacity: 1; color: #aaacaf;"><span class="glyphicon glyphicon-envelope"></span>  info@rrh.com</a></li>
                                <li style="color: #aaacaf;"> <span class="glyphicon glyphicon-map-marker"></span>  286 Fifth Avenue 8th Floor, New York, New York 10001 </li>
                                <li style="display:none; color: #aaacaf;"><span class="glyphicon glyphicon-map-marker"></span>  286 Fifth Avenue 8th Floor &nbsp; &nbsp; &nbsp; New York, New York 10001 </li>
                            </ul>
                        </div>
                        <div class="social">
                                  <a target="_blank" href="#" style="color: #fff">
                                      <i class="fa fa-twitter" style="font-size:25px"></i>
                                  </a>&nbsp;&nbsp;&nbsp;
                                  <a target="_blank" href="#" style="color: #fff">
                                      <i class="fa fa-facebook-square" style="font-size:25px"></i>
                                  </a>&nbsp;&nbsp;&nbsp;
                                  <a target="_blank" href="#" style="color: #fff">
                                      <i class="fa fa-instagram" style="font-size:25px"></i>
                                  </a>&nbsp;&nbsp;&nbsp;
                                  <a target="_blank" href="#" style="color: #fff">
                                      <i class="fa fa-linkedin" style="font-size:25px"></i>
                                  </a>
                            </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>

app/views/welcome/_navbarStaticPages.html.erb
<!DOCTYPE html>
    <html lang="en">
        <head>
            <script type="text/javascript">
         		$(document).ready(function() {
			        $('li.active').removeClass('active');
			        $('a[href="' + location.pathname + '"]').closest('li').addClass('active'); 
      			});
        	</script>
        	<style type="text/css">
        		.navbar{
        			margin-bottom: 0px;
        		}
        		
        		
        	</style>
        </head>
        <body>
        	<nav class="navbar navbar-inverse navbar-fixed-top">
				<div class="container-fluid">
				    <div class="navbar-header">
				    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				    		<span class="icon-bar"></span>
				    		<span class="icon-bar"></span>
				    		<span class="icon-bar"></span>
				    	</button>
				    	<a class="navbar-brand" href="/home"><img src="/assets/redox_logo.png"style=" width: 35px; height:33px; display: inline-block; ">
  							<span style="display: inline-block;">Redox Realty Group</span>
				    		
				    	</a>
				    </div>
			    	<div class="collapse navbar-collapse" id="myNavbar">  
						<ul class="nav navbar-nav navbar-right">
							<li><a href="/home">Home</a></li>
							<li><a href="/agents">Agents</a></li>
							<li><a href="/aboutus">About Us</a></li>
							<li><a href="/contactus">Contact Us</a></li>
							<li><a href="/login"><span class="glyphicon glyphicon-user"></span> Login</a></li>
						</ul>
			    	</div>
			  	</div>
			</nav>
		</body>
</html>